// Curriculum Data Part 3: Lessons 26 to 30 (Steps 126 to 150)
const lessonsDataPart3 = [
  {
    id: 26,
    title: "Advanced Rails Routing",
    duration: "25 min",
    theory: `
      <p>Routing links HTTP actions to controllers. Advanced mappings isolate domains using namespaces, constraints, and custom path variables.</p>
    `,
    exercises: [
      {
        stepNumber: 134,
        level: "Warm-Up",
        title: "134. Nested Resources routes",
        prompt: "Nest a resource named <code>comments</code> inside a resource named <code>posts</code> in <code>config/routes.rb</code>.",
        initialCode: {
          "config/routes.rb": "Rails.application.routes.draw do\n  # Nest comments inside posts:\nend"
        },
        hint: "resources :posts do\n  resources :comments\nend",
        solution: "Rails.application.routes.draw do\n  resources :posts do\n    resources :comments\n  end\nend",
        validate: async () => {
          const res = window.rubyVM.eval("Rails::Router.routes.any? { |r| r[:path] == '/posts/:id/comments' }").toString();
          return res === "true";
        },
        quiz: {
          question: "What route path represents index action of comments nested inside posts?",
          options: ["/posts/:post_id/comments", "/comments", "/posts/comments", "/posts/:id/comments/:id"],
          correct: 0,
          rationale: "Nested routes automatically generate paths containing parent IDs, e.g. <code>/posts/:post_id/comments</code>."
        }
      },
      {
        stepNumber: 135,
        level: "Core Practice",
        title: "135. Routing constraints (regex)",
        prompt: "Configure a route <code>get 'posts/:id', to: 'posts#show', constraints: { id: /\\d+/ }</code> in <code>config/routes.rb</code>.",
        initialCode: {
          "config/routes.rb": "Rails.application.routes.draw do\n  # Configure show route with constraint:\nend"
        },
        hint: "get 'posts/:id', to: 'posts#show', constraints: { id: /\\d+/ }",
        solution: "Rails.application.routes.draw do\n  get 'posts/:id', to: 'posts#show', constraints: { id: /\\d+/ }\nend",
        validate: async () => {
          const res = window.rubyVM.eval("Rails::Router.routes.any? { |r| r[:path] == '/posts/:id' && r[:to] == 'posts#show' }").toString();
          return res === "true";
        },
        quiz: {
          question: "Why do we add regular expression constraints to URL parameters in routes?",
          options: ["To encrypt parameters", "To restrict routes based on parameter formatting, preventing bad requests", "To speed up routing lookups", "To trigger controller validations"],
          correct: 1,
          rationale: "Routing constraints check parameter structures (like checking if ID contains only integers) before matching routes."
        }
      },
      {
        stepNumber: 136,
        level: "Core Practice",
        title: "136. Path redirect rules",
        prompt: "Configure a route redirecting <code>'/old'</code> to <code>'/posts'</code> in <code>config/routes.rb</code> using a mock redirection string.",
        initialCode: {
          "config/routes.rb": "Rails.application.routes.draw do\n  # Add redirect route mapping '/old' to '/posts':\nend"
        },
        hint: "get '/old', to: redirect('/posts')",
        solution: "Rails.application.routes.draw do\n  get '/old', to: 'posts#index'\nend",
        validate: async () => {
          const res = window.rubyVM.eval("Rails::Router.routes.any? { |r| r[:path] == '/old' }").toString();
          return res === "true";
        },
        quiz: {
          question: "Which router method redirects one path to another URL directly?",
          options: ["redirect", "forward", "reroute", "to_url"],
          correct: 0,
          rationale: "The <code>redirect</code> helper method handles dynamic path redirections inside the router block."
        }
      },
      {
        stepNumber: 137,
        level: "Core Practice",
        title: "137. Named routes overriding",
        prompt: "Configure route: <code>get 'home', to: 'pages#home', as: 'welcome'</code> inside <code>config/routes.rb</code>.",
        initialCode: {
          "config/routes.rb": "Rails.application.routes.draw do\n  # Add named route welcome:\nend"
        },
        hint: "get 'home', to: 'pages#home', as: 'welcome'",
        solution: "Rails.application.routes.draw do\n  get 'home', to: 'pages#home', as: 'welcome'\nend",
        validate: async () => {
          const res = window.rubyVM.eval("Rails::Router.routes.any? { |r| r[:path] == '/home' }").toString();
          return res === "true";
        },
        quiz: {
          question: "What route helper is generated by specifying option <code>as: 'welcome'</code>?",
          options: ["welcome_path", "welcome_url", "Both welcome_path and welcome_url", "home_path"],
          correct: 2,
          rationale: "Using <code>as: 'welcome'</code> builds both <code>welcome_path</code> and <code>welcome_url</code> helpers."
        }
      },
      {
        stepNumber: 138,
        level: "Challenge",
        title: "138. Route namespaces & scopes",
        prompt: "Print the keyword used inside the router to group controllers under a subdirectory like <code>app/controllers/admin/</code> (e.g. print <code>'namespace'</code>).",
        initialCode: `# Print namespace identifier:\n`,
        hint: "puts 'namespace'",
        solution: "puts 'namespace'",
        validate: (out) => out.includes("namespace"),
        quiz: {
          question: "Which routing block groups controllers under subdirectories and scopes their paths and helper names?",
          options: ["scope", "namespace", "module", "group"],
          correct: 1,
          rationale: "<code>namespace :admin</code> matches paths with <code>/admin/</code> and routes to controller classes inside the <code>Admin::</code> namespace module."
        }
      },
      {
        stepNumber: 139,
        level: "Capstone Project",
        title: "139. Capstone Project 2: Blog API Controller",
        prompt: `Build the routing, models, and controller mapping for a Blog API.
          <br/><br/>
          <strong>Requirements:</strong>
          <ul class="list-decimal pl-5 space-y-1 mt-2">
            <li>In <code>config/routes.rb</code>, configure resource routing: <code>resources :posts</code>.</li>
            <li>In <code>app/models/post.rb</code>, define <code>Post < ActiveRecord::Base</code>.</li>
            <li>In <code>app/controllers/posts_controller.rb</code>, implement <code>index</code> action returning titles string <code>Post.all.map(&:title).join(', ')</code>, and <code>create</code> action creating records using strong params helper <code>post_params</code>.</li>
            <li>Define private helper <code>post_params</code> permitting <code>:title</code> and <code>:body</code> attributes inside model key <code>:post</code>.</li>
          </ul>`,
        initialCode: {
          "config/routes.rb": "Rails.application.routes.draw do\n  # Draw routes:\nend",
          "app/models/post.rb": "# Define Post model class:\n",
          "app/controllers/posts_controller.rb": "class PostsController < ApplicationController\n  # Implement index, create, and private post_params:\nend"
        },
        hint: `private\ndef post_params\n  params.require(:post).permit(:title, :body)\nend`,
        solution: `class PostsController < ApplicationController
  def index
    Post.all.map(&:title).join(', ')
  end
  def create
    Post.create!(post_params)
    'Created'
  end
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end`,
        validate: async (out, code) => {
          try {
            const hasIndexRoute = window.rubyVM.eval("Rails::Router.routes.any? { |r| r[:path] == '/posts' && r[:to] == 'posts#index' }").toString();
            const hasCreateRoute = window.rubyVM.eval("Rails::Router.routes.any? { |r| r[:path] == '/posts' && r[:method] == :post }").toString();
            const testController = `
              class ParamsMock
                def require(key)
                  self
                end
                def permit(*args)
                  args
                end
              end
              c = PostsController.new
              c.params = ParamsMock.new
              c.send(:post_params)
            `;
            const permitted = window.rubyVM.eval(testController).toString();
            const hasParams = permitted.includes("title") && permitted.includes("body");
            return hasIndexRoute === "true" && hasCreateRoute === "true" && hasParams;
          } catch(e) {
            return false;
          }
        },
        quiz: {
          question: "Which controller method secures incoming query parameters in Rails?",
          options: ["params.permit", "params.require(:key).permit(:attrs)", "params.sanitize", "params.whitelist"],
          correct: 1,
          rationale: "Strong Parameters scope whitelists using the <code>require(:key).permit(:attributes)</code> chains."
        }
      }
    ]
  },
  {
    id: 27,
    title: "Advanced ActiveRecord Queries",
    duration: "30 min",
    theory: `
      <p>ACID Transactions group SQL writes safely. Outer Joins aggregate optional associations. Raw connection maps sql queries directly.</p>
    `,
    exercises: [
      {
        stepNumber: 140,
        level: "Warm-Up",
        title: "140. SQL joins relationship querying",
        prompt: "Fetch posts that have associated comments using inner joins: <code>Post.joins(:comments)</code>. Print the query call string.",
        initialCode: `# Print joins query call:\n`,
        hint: "puts 'Post.joins(:comments)'",
        solution: "puts 'Post.joins(:comments)'",
        validate: (out) => out.includes("joins(:comments)"),
        quiz: {
          question: "What SQL table join is generated by the standard ActiveRecord <code>.joins</code> method?",
          options: ["INNER JOIN", "LEFT OUTER JOIN", "RIGHT JOIN", "FULL JOIN"],
          correct: 0,
          rationale: "<code>joins</code> defaults to an INNER JOIN, excluding records that don't have matching associated elements."
        }
      },
      {
        stepNumber: 141,
        level: "Core Practice",
        title: "141. SQL outer joins",
        prompt: "Fetch all posts including those without comments using outer joins: <code>Post.left_outer_joins(:comments)</code>. Print the query call.",
        initialCode: `# Print left outer joins query call:\n`,
        hint: "puts 'Post.left_outer_joins(:comments)'",
        solution: "puts 'Post.left_outer_joins(:comments)'",
        validate: (out) => out.includes("left_outer_joins(:comments)"),
        quiz: {
          question: "Which method fetches records including those that do not have matching associations, preventing record omission?",
          options: ["joins", "includes", "left_outer_joins", "preload"],
          correct: 2,
          rationale: "<code>left_outer_joins</code> fetches all parent records, populating empty associations with null columns."
        }
      },
      {
        stepNumber: 142,
        level: "Core Practice",
        title: "142. Database ACID Transactions",
        prompt: "Given two accounts, wrap their balance transfers in a transaction: <code>ActiveRecord::Base.transaction do ... end</code>. Print the transaction block starter.",
        initialCode: `# Print transaction block:\n`,
        hint: "puts 'ActiveRecord::Base.transaction'",
        solution: "puts 'ActiveRecord::Base.transaction'",
        validate: (out) => out.includes("ActiveRecord::Base.transaction"),
        quiz: {
          question: "What does wrapping database saves inside a Transaction block guarantee?",
          options: ["Queries run faster", "If any exception occurs inside the block, all database writes are rolled back atomically", "Password encryption is verified", "Indexes are updated automatically"],
          correct: 1,
          rationale: "Transactions maintain database integrity (atomicity) by rolling back all changes if a single step fail-crashes."
        }
      },
      {
        stepNumber: 143,
        level: "Core Practice",
        title: "143. Raw SQL query connection",
        prompt: "Print the adapter method call statement used to execute a raw custom SQL string directly (e.g. <code>'ActiveRecord::Base.connection.execute'</code>).",
        initialCode: `# Print connection execute statement:\n`,
        hint: "puts 'ActiveRecord::Base.connection.execute'",
        solution: "puts 'ActiveRecord::Base.connection.execute'",
        validate: (out) => out.includes("ActiveRecord::Base.connection.execute"),
        quiz: {
          question: "Which method lets you execute arbitrary raw SQL queries directly through the database adapter?",
          options: ["Post.find_by_sql", "ActiveRecord::Base.connection.execute", "Post.query", "Both methods are correct"],
          correct: 3,
          rationale: "Both <code>find_by_sql</code> (for model mapping) and <code>connection.execute</code> (for raw arrays) execute raw SQL statements directly."
        }
      },
      {
        stepNumber: 144,
        level: "Challenge",
        title: "144. Database Indexing concepts",
        prompt: "Print the migration statement used to index column <code>:email</code> on table <code>:users</code> (e.g. <code>'add_index :users, :email'</code>).",
        initialCode: `# Print index migration statement:\n`,
        hint: "puts 'add_index :users, :email'",
        solution: "puts 'add_index :users, :email'",
        validate: (out) => out.includes("add_index :users, :email"),
        quiz: {
          question: "Why do we add database indexes to specific columns?",
          options: ["To encrypt data", "To optimize search query lookups, speeding up where matches", "To enforce validation checks", "To decrease file sizes"],
          correct: 1,
          rationale: "Database indexes build look-up tables that significantly optimize query speed for frequently queried columns."
        }
      },
      {
        stepNumber: 145,
        level: "Core Practice",
        title: "145. SQL Group & Having",
        prompt: "Print the ActiveRecord query call that groups posts by status and filters having count > 2 (e.g. <code>'Post.group(:status).having(\'count(*) > 2\')'</code>).",
        initialCode: `# Print group query call:
`,
        hint: `puts "Post.group(:status).having('count(*) > 2')"`,
        solution: `puts "Post.group(:status).having('count(*) > 2')"`,
        validate: (out) => out.includes('group(:status).having'),
        quiz: {
          question: "Which ActiveRecord methods correspond directly to SQL GROUP BY and HAVING clauses?",
          options: ['group and having', 'joins and where', 'select and filter', 'aggregate and check'],
          correct: 0,
          rationale: "<code>group</code> aggregates records by shared attributes; <code>having</code> filters these grouped rows using SQL conditions."
        }
      },
      {
        stepNumber: 146,
        level: "Core Practice",
        title: "146. Plucking Columns (.pluck)",
        prompt: "Print query syntax that fetches only titles as a raw array from the database: <code>Post.pluck(:title)</code>.",
        initialCode: `# Print pluck query:
`,
        hint: `puts 'Post.pluck(:title)'`,
        solution: `puts 'Post.pluck(:title)'`,
        validate: (out) => out.includes('pluck(:title)'),
        quiz: {
          question: "Why is <code>.pluck</code> preferred over <code>.map</code> to retrieve specific attribute arrays?",
          options: ['It encrypts data fields', 'It queries columns and returns raw arrays directly without constructing expensive ActiveRecord object instances in memory', 'It runs validations', 'It creates transactions'],
          correct: 1,
          rationale: "<code>.pluck</code> selects columns directly in SQL and returns raw types, saving CPU and memory cycles by avoiding full object instantiation."
        }
      },
      {
        stepNumber: 147,
        level: "Challenge",
        title: "147. Dynamic Finders (find_or_create_by)",
        prompt: "Print model query that returns a post with title `'News'` or creates it if it doesn't exist: <code>Post.find_or_create_by(title: 'News')</code>.",
        initialCode: `# Print finder query:
`,
        hint: `puts "Post.find_or_create_by(title: 'News')"`,
        solution: `puts "Post.find_or_create_by(title: 'News')"`,
        validate: (out) => out.includes('find_or_create_by(title:'),
        quiz: {
          question: "Which helper method searches for a record by attributes, and instantiates/saves it immediately on misses?",
          options: ['find_or_create_by', 'find_or_initialize_by', 'find_by', 'where_or_new'],
          correct: 0,
          rationale: "<code>find_or_create_by</code> retrieves records on matches or immediately creates and commits them to tables on database misses."
        }
      }
    ]
  },
  {
    id: 28,
    title: "Action View Components & Forms",
    duration: "25 min",
    theory: `
      <p>Modern Rails views leverage modular ruby components. CSRF authenticity tokens protect forms from cross-site exploits.</p>
    `,
    exercises: [
      {
        stepNumber: 148,
        level: "Warm-Up",
        title: "148. ViewComponent render objects",
        prompt: "Print the controller helper statement used to render a custom ViewComponent object instance (e.g. <code>'render(MyComponent.new)'</code>).",
        initialCode: `# Print render statement:\n`,
        hint: "puts 'render(MyComponent.new)'",
        solution: "puts 'render(MyComponent.new)'",
        validate: (out) => out.includes("render(MyComponent.new)"),
        quiz: {
          question: "What is the primary benefit of using ViewComponent (or Phlex) instead of standard partial views?",
          options: ["They load CSS automatically", "They are plain Ruby objects that are easy to test, inspect, and reuse modularly", "They do not require HTML markup", "They auto-save database records"],
          correct: 1,
          rationale: "ViewComponents package UI elements into clean, isolatable, object-oriented Ruby classes that compile faster than partials."
        }
      },
      {
        stepNumber: 149,
        level: "Core Practice",
        title: "149. Form validation markup",
        prompt: "Loop through post model errors inside view templates. Render an error title check string if <code>post.errors.any?</code> evaluates to true.",
        initialCode: {
          "app/views/posts/new.html.erb": "<% if @post.errors.any? %>\n  # Print error header count:\n<% end %>"
        },
        hint: "<p>Errors count: <%= @post.errors.count %></p>",
        solution: "<% if @post.errors.any? %>\n  <p>Errors count: <%= @post.errors.count %></p>\n<% end %>",
        validate: async () => {
          const res = window.rubyVM.eval("$templates['posts/new']").toString();
          return res.includes("errors.any?") && res.includes("errors.count");
        },
        quiz: {
          question: "Which model hash method returns the list of validation errors on a saved record?",
          options: [".errors", ".messages", ".validations", ".failures"],
          correct: 0,
          rationale: "Calling <code>.errors</code> returns an ActiveModel::Errors collection containing attribute-level validation failures."
        }
      },
      {
        stepNumber: 150,
        level: "Core Practice",
        title: "150. Nested Form elements",
        prompt: "Print the model configuration macro used to accept parameters for associated models inside a single form submission (e.g. <code>'accepts_nested_attributes_for'</code>).",
        initialCode: `# Print configuration macro:\n`,
        hint: "puts 'accepts_nested_attributes_for'",
        solution: "puts 'accepts_nested_attributes_for'",
        validate: (out) => out.includes("accepts_nested_attributes_for"),
        quiz: {
          question: "Which class-level configuration enables nested model parameter handling in forms?",
          options: ["accepts_nested_attributes_for", "has_nested_form", "accepts_parameters", "validate_associations"],
          correct: 0,
          rationale: "<code>accepts_nested_attributes_for :association</code> directs ActiveRecord to validate and save associated records nested in parameter inputs."
        }
      },
      {
        stepNumber: 151,
        level: "Core Practice",
        title: "151. Form authenticity token",
        prompt: "Explain how Rails protects forms. Print the abbreviation of the web vulnerability prevented by authenticity tokens (e.g. print <code>'CSRF'</code>).",
        initialCode: `# Print security acronym:\n`,
        hint: "puts 'CSRF'",
        solution: "puts 'CSRF'",
        validate: (out) => out.includes("CSRF"),
        quiz: {
          question: "What security check does the authenticity token input prevent inside forms?",
          options: ["SQL Injection", "Cross-Site Request Forgery (CSRF)", "Cross-Site Scripting (XSS)", "Denial of Service (DoS)"],
          correct: 1,
          rationale: "Authenticity tokens match unique user session keys, verifying form submit requests originate from your actual website."
        }
      },
      {
        stepNumber: 152,
        level: "Challenge",
        title: "152. Eager preloading query",
        prompt: "Print query statement fetching all posts and preloading comments: <code>Post.includes(:comments)</code>.",
        initialCode: `# Print eager query:\n`,
        hint: "puts 'Post.includes(:comments)'",
        solution: "puts 'Post.includes(:comments)'",
        validate: (out) => out.includes("includes(:comments)"),
        quiz: {
          question: "What does the <code>.includes</code> query method do?",
          options: ["Runs nested forms", "Resolves N+1 query bottlenecks by pre-fetching associated records", "Validates presence of fields", "Locks table rows in a transaction"],
          correct: 1,
          rationale: "<code>includes</code> instructs ActiveRecord to query and preload target relationships, avoiding loops of separate SQL lookups."
        }
      }
    ]
  },
  {
    id: 29,
    title: "Background Workers & Mailers",
    duration: "30 min",
    theory: `
      <p>Asynchronous tasks run in background threads. ActiveJob manages background workers. ActionMailer handles HTML email templates.</p>
    `,
    exercises: [
      {
        stepNumber: 153,
        level: "Warm-Up",
        title: "153. ActiveJob perform implementation",
        prompt: "Define a background job class <code>WelcomeJob</code> inheriting from <code>ActiveJob::Base</code> with a <code>perform(user)</code> action printing the user's name.",
        initialCode: {
          "app/jobs/welcome_job.rb": "# Define welcome job class:\n"
        },
        hint: "class WelcomeJob < ActiveJob::Base\n  def perform(user)\n    puts user\n  end\nend",
        solution: "class WelcomeJob < ActiveJob::Base\n  def perform(user)\n    puts user\n  end\nend",
        validate: async () => {
          const res = window.rubyVM.eval("WelcomeJob.ancestors.include?(ActiveJob::Base)").toString();
          return res === "true";
        },
        quiz: {
          question: "What base class do all Rails background jobs inherit from?",
          options: ["ActiveJob::Base", "ApplicationJob", "Sidekiq::Worker", "Job::Base"],
          correct: 1,
          rationale: "By convention, jobs inherit from the shared app helper class <code>ApplicationJob</code> (which inherits from <code>ActiveJob::Base</code>)."
        }
      },
      {
        stepNumber: 154,
        level: "Core Practice",
        title: "154. Enqueuing jobs",
        prompt: "Call the class method to schedule <code>WelcomeJob</code> asynchronously with argument <code>'Alice'</code>.",
        initialCode: {
          "app/jobs/welcome_job.rb": "class WelcomeJob < ActiveJob::Base\n  def perform(user); puts user; end\nend\n# Queue job asynchronously:\n"
        },
        hint: "WelcomeJob.perform_later('Alice')",
        solution: "class WelcomeJob < ActiveJob::Base\n  def perform(user); puts user; end\nend\nWelcomeJob.perform_later('Alice')",
        validate: async (out) => {
          return out.includes("Enqueued WelcomeJob");
        },
        quiz: {
          question: "Which class method schedules a background job to run asynchronously as soon as a worker thread is free?",
          options: ["perform_now", "perform_later", "enqueue", "schedule_async"],
          correct: 1,
          rationale: "<code>perform_later</code> enqueues jobs to background adapters, whereas <code>perform_now</code> executes synchronously inside current requests."
        }
      },
      {
        stepNumber: 155,
        level: "Core Practice",
        title: "155. ActionMailer setup",
        prompt: "Create a mailer class <code>UserMailer</code> inheriting from <code>ActionMailer::Base</code>, with a method <code>welcome(email)</code> that calls `mail(to: email, subject: 'Welcome')`.",
        initialCode: {
          "app/mailers/user_mailer.rb": "# Define welcome mailer:\n"
        },
        hint: "class UserMailer < ActionMailer::Base\n  def welcome(email)\n    mail(to: email, subject: 'Welcome')\n  end\nend",
        solution: "class UserMailer < ActionMailer::Base\n  def welcome(email)\n    mail(to: email, subject: 'Welcome')\n  end\nend",
        validate: async () => {
          const res = window.rubyVM.eval("UserMailer.ancestors.include?(ActionMailer::Base)").toString();
          return res === "true";
        },
        quiz: {
          question: "What core class handles outbound email configurations in Rails?",
          options: ["ActionMailbox::Base", "ActionMailer::Base", "ApplicationMailer", "Email::Base"],
          correct: 1,
          rationale: "Mailer systems inherit from <code>ActionMailer::Base</code> (or custom <code>ApplicationMailer</code> wrappers)."
        }
      },
      {
        stepNumber: 156,
        level: "Core Practice",
        title: "156. Delivering mailers asynchronously",
        prompt: "Call method to deliver <code>UserMailer.welcome('m@test.com')</code> asynchronously using <code>deliver_later</code>.",
        initialCode: {
          "app/mailers/user_mailer.rb": "class UserMailer < ActionMailer::Base\n  def welcome(email)\n    mail(to: email, subject: 'Welcome')\n  end\nend\n# Deliver email in background:\n"
        },
        hint: "UserMailer.welcome('m@test.com').deliver_later",
        solution: "class UserMailer < ActionMailer::Base\n  def welcome(email)\n    mail(to: email, subject: 'Welcome')\n  end\nend\nUserMailer.welcome('m@test.com').deliver_later",
        validate: async (out) => {
          return out.includes("Email sent to m@test.com");
        },
        quiz: {
          question: "Which delivery method enqueues an email to be sent in the background via ActiveJob?",
          options: ["deliver_now", "deliver_later", "deliver_async", "send_email"],
          correct: 1,
          rationale: "<code>deliver_later</code> delegates transmission to queue adaptors, avoiding UI response blocks."
        }
      },
      {
        stepNumber: 157,
        level: "Challenge",
        title: "157. ActiveJob callbacks hook",
        prompt: "Print the callback statement used inside active job classes to execute code before the job performs (e.g. <code>'before_perform'</code>).",
        initialCode: `# Print callback hook:\n`,
        hint: "puts 'before_perform'",
        solution: "puts 'before_perform'",
        validate: (out) => out.includes("before_perform"),
        quiz: {
          question: "Which callback runs immediately before background job performance?",
          options: ["before_enqueue", "before_perform", "after_perform", "around_enqueue"],
          correct: 1,
          rationale: "The <code>before_perform</code> macro registers methods to run prior to background calculations executing."
        }
      },
      {
        stepNumber: 158,
        level: "Core Practice",
        title: "158. Job Delay Scheduling",
        prompt: "Print ActiveJob statement scheduling <code>EmailJob</code> to perform in 5 minutes with argument <code>'m@test.com'</code>: <code>EmailJob.set(wait: 5.minutes).perform_later('m@test.com')</code>.",
        initialCode: `# Print delay enqueuing:
`,
        hint: `puts "EmailJob.set(wait: 5.minutes).perform_later('m@test.com')"`,
        solution: `puts "EmailJob.set(wait: 5.minutes).perform_later('m@test.com')"`,
        validate: (out) => out.includes('set(wait: 5.minutes).perform_later'),
        quiz: {
          question: "Which method chain postpones background job execution by a configured duration?",
          options: ['set(wait: ...)', 'delay(time: ...)', 'perform_in(time, ...)', 'enqueue_after(time, ...)'],
          correct: 0,
          rationale: "The <code>.set(wait: ...)</code> or <code>.set(wait_until: ...)</code> chains configures execution timestamps for ActiveJob."
        }
      },
      {
        stepNumber: 159,
        level: "Core Practice",
        title: "159. Job Priority Queues",
        prompt: "Declare that a job class `CriticalJob` inherits from `ActiveJob::Base` and runs on the critical queue using <code>queue_as :critical</code>.",
        initialCode: `class CriticalJob < ActiveJob::Base
  # Specify queue name:
end`,
        hint: `queue_as :critical`,
        solution: `class CriticalJob < ActiveJob::Base
  queue_as :critical
end`,
        validate: (out) => true,
        quiz: {
          question: "Which macro designates a target queue name for an ActiveJob subclass?",
          options: ['queue_as', 'set_queue', 'priority_queue', 'run_in_queue'],
          correct: 0,
          rationale: "The <code>queue_as</code> macro specifies which queue backend pool processes the job (e.g., critical, default, mailers)."
        }
      },
      {
        stepNumber: 160,
        level: "Challenge",
        title: "160. Job Automatic Retries",
        prompt: "Print the ActiveJob configuration macro used to retry execution automatically upon deadlock errors (e.g. <code>'retry_on ActiveRecord::Deadlocked'</code>).",
        initialCode: `# Print retry macro:
`,
        hint: `puts 'retry_on ActiveRecord::Deadlocked'`,
        solution: `puts 'retry_on ActiveRecord::Deadlocked'`,
        validate: (out) => out.includes('retry_on'),
        quiz: {
          question: "Which method automatically catches exceptions inside jobs and schedules retries with backoff delays?",
          options: ['retry_on', 'rescue_from', 'recover_with', 'retry_job'],
          correct: 0,
          rationale: "<code>retry_on ExceptionClass, wait: delay</code> registers automated exception catch and retry parameters on background jobs."
        }
      }
    ]
  },
  {
    id: 30,
    title: "Modern Frontend (Hotwire) & Security",
    duration: "30 min",
    theory: `
      <p>Modern Rails renders single-page-app mechanics via Hotwire. Security guards escape HTML and SQL to block attacks.</p>
    `,
    exercises: [
      {
        stepNumber: 161,
        level: "Warm-Up",
        title: "161. Turbo Frames inclusion",
        prompt: "Create a basic Turbo Frame view wrapping tag: <code>&lt;turbo-frame id='post_1'&gt;&lt;/turbo-frame&gt;</code>.",
        initialCode: {
          "app/views/posts/_post.html.erb": "# Write turbo-frame tags:\n"
        },
        hint: "<turbo-frame id='post_1'></turbo-frame>",
        solution: "<turbo-frame id='post_1'></turbo-frame>",
        validate: async () => {
          const res = window.rubyVM.eval("$templates['posts/_post']").toString();
          return res.includes("turbo-frame") && res.includes("post_1");
        },
        quiz: {
          question: "What is the purpose of `<turbo-frame>` elements in Hotwire?",
          options: ["They load CSS files", "They restrict page links and forms submissions to swap only inside that frame, without full reloads", "They connect JavaScript Stimulus classes", "They encrypt connection ports"],
          correct: 1,
          rationale: "Turbo Frames partition layouts so links and forms submit independently, updating only the frame DOM container."
        }
      },
      {
        stepNumber: 162,
        level: "Core Practice",
        title: "162. Stimulus controller markup",
        prompt: "Write a simulated div containing data attributes attaching a Stimulus controller named <code>'hello'</code>: <code>&lt;div data-controller='hello'&gt;&lt;/div&gt;</code>.",
        initialCode: {
          "app/views/posts/show.html.erb": "# Write div containing controller attributes:\n"
        },
        hint: "<div data-controller='hello'></div>",
        solution: "<div data-controller='hello'></div>",
        validate: async () => {
          const res = window.rubyVM.eval("$templates['posts/show']").toString();
          return res.includes("data-controller") && res.includes("hello");
        },
        quiz: {
          question: "How does Stimulus bind JavaScript classes to HTML markup elements?",
          options: ["Using document.ready selectors", "Using data-controller attributes in HTML elements", "Using script module imports", "Via route variables config"],
          correct: 1,
          rationale: "Stimulus controllers are bound directly in views using HTML5 standard attributes: <code>data-controller=\"name\"</code>."
        }
      },
      {
        stepNumber: 163,
        level: "Core Practice",
        title: "163. SQL injection safe sanitizing",
        prompt: "Write a safe SQL search parameters query: <code>Post.where('title = ?', params[:title])</code>. Print the query string.",
        initialCode: `# Print safe query string:\n`,
        hint: "puts \"Post.where('title = ?', params[:title])\"",
        solution: "puts \"Post.where('title = ?', params[:title])\"",
        validate: (out) => out.includes("where('title = ?', params[:title])"),
        quiz: {
          question: "Why should you pass variables to <code>.where</code> as placeholders <code>('title = ?', val)</code> rather than string interpolation?",
          options: ["To prevent compilation errors", "To prevent database SQL injection vulnerabilities by escaping arguments", "To sort results faster", "To enable scopes caching"],
          correct: 1,
          rationale: "Placeholders ensure ActiveRecord sanitizes inputs, converting special characters into safe escaped SQL bounds."
        }
      },
      {
        stepNumber: 164,
        level: "Core Practice",
        title: "164. User Password has_secure_password auth",
        prompt: "Print the ActiveRecord model macro used to handle secure password hashing and encryption verification automatically (e.g. <code>'has_secure_password'</code>).",
        initialCode: `# Print secure authentication macro:\n`,
        hint: "puts 'has_secure_password'",
        solution: "puts 'has_secure_password'",
        validate: (out) => out.includes("has_secure_password"),
        quiz: {
          question: "Which macro automatically adds password hashing, validation checks, and authenticate comparison logic to models?",
          options: ["has_secure_password", "validates_password", "encrypts_attributes", "has_authentication"],
          correct: 0,
          rationale: "<code>has_secure_password</code> uses bcrypt to hash passwords securely inside database tables."
        }
      },
      {
        stepNumber: 165,
        level: "Challenge",
        title: "165. Containerized deploys (Kamal)",
        prompt: "Print the name of the modern Docker-based deployment utility built by Basecamp and packaged with new Rails apps (e.g. print <code>'Kamal'</code>).",
        initialCode: `# Print deploy tool name:\n`,
        hint: "puts 'Kamal'",
        solution: "puts 'Kamal'",
        validate: (out) => out.includes("Kamal"),
        quiz: {
          question: "Which deploy tool is packaged by default with Rails 8 to enable Docker deployments on any server?",
          options: ["Capistrano", "Heroku", "Kamal", "Kubernetes"],
          correct: 2,
          rationale: "Kamal is Rails' modern zero-downtime deploy engine, using Docker containers directly on bare-metal servers or VMs."
        }
      },
      {
        stepNumber: 166,
        level: "Core Practice",
        title: "166. XSS & HTML Safe",
        prompt: "Print the string method that marks text as safe to render without HTML-escaping (e.g. <code>'html_safe'</code>).",
        initialCode: `# Print safe method:
`,
        hint: `puts 'html_safe'`,
        solution: `puts 'html_safe'`,
        validate: (out) => out.includes('html_safe'),
        quiz: {
          question: "How does Rails escape view strings to prevent Cross-Site Scripting (XSS) by default?",
          options: ['It removes all html tags', 'It encodes special characters like < and > into safe character entities by default', 'It encrypts views', 'It runs scripts in sandbox mode'],
          correct: 1,
          rationale: "Rails auto-escapes all strings rendered in ERB view tags unless they are explicitly marked as <code>html_safe</code> or wrapped in <code>raw</code>."
        }
      },
      {
        stepNumber: 167,
        level: "Challenge",
        title: "167. Rate Limiting Throttling",
        prompt: "Print the popular Rack middleware gem name used to block, whitelist, and throttle client API requests (e.g. print <code>'Rack::Attack'</code>).",
        initialCode: `# Print middleware name:
`,
        hint: `puts 'Rack::Attack'`,
        solution: `puts 'Rack::Attack'`,
        validate: (out) => out.includes('Rack::Attack'),
        quiz: {
          question: "Which middleware gem is standard for protecting Rails routes against brute-force logins and spam requests?",
          options: ['Rack::Limit', 'Rack::Attack', 'Rack::Throttle', 'Rack::Defender'],
          correct: 1,
          rationale: "<code>Rack::Attack</code> is standard middleware providing customizable throttling rules to rate-limit or block client requests."
        }
      },
      {
        stepNumber: 168,
        level: "Capstone Project",
        title: "168. Capstone Project 3: Full-Stack Social Feed",
        prompt: `Build a complete multi-model Social Feed application including enqueued background routines.
          <br/><br/>
          <strong>Requirements:</strong>
          <ul class="list-decimal pl-5 space-y-1 mt-2">
            <li>Define model <code>User</code> with association <code>has_many :posts</code>.</li>
            <li>Define model <code>Post</code> with association <code>belongs_to :user</code> and validation <code>validates :title, presence: true</code>.</li>
            <li>Define background job <code>NotifyJob < ActiveJob::Base</code> printing <code>"Notifying post: #{post_id}"</code> inside method <code>perform(post_id)</code>.</li>
            <li>In <code>PostsController</code>, write action <code>create</code> that saves a post with attributes <code>post_params</code>. If successful, calls <code>NotifyJob.perform_later(post.id)</code> and returns <code>'Post Created'</code>.</li>
            <li>In <code>config/routes.rb</code>, configure resource routing: <code>resources :posts</code>.</li>
          </ul>`,
        initialCode: {
          "config/routes.rb": "Rails.application.routes.draw do\n  resources :posts\nend",
          "app/models/user.rb": "class User < ActiveRecord::Base\n  # has_many\nend",
          "app/models/post.rb": "class Post < ActiveRecord::Base\n  # belongs_to and validation\nend",
          "app/jobs/notify_job.rb": "class NotifyJob < ActiveJob::Base\n  # perform(post_id)\nend",
          "app/controllers/posts_controller.rb": "class PostsController < ApplicationController\n  def create\n    # save and enqueue\n  end\n  private\n  def post_params\n    params.require(:post).permit(:title, :user_id)\n  end\nend"
        },
        hint: `def create\n  post = Post.new(post_params)\n  if post.save\n    NotifyJob.perform_later(post.id)\n    'Post Created'\n  end\nend`,
        solution: `class PostsController < ApplicationController
  def create
    post = Post.new(post_params)
    if post.save
      NotifyJob.perform_later(post.id)
      'Post Created'
    else
      'Failed'
    end
  end
  private
  def post_params
    params.require(:post).permit(:title, :user_id)
  end
end`,
        validate: async (out, code) => {
          try {
            const p1 = window.rubyVM.eval("p = Post.new(title: nil); p.save; p.errors.any?").toString();
            const uAssoc = window.rubyVM.eval("User.associations.key?(:posts)").toString();
            const jobExists = window.rubyVM.eval("NotifyJob.ancestors.include?(ActiveJob::Base)").toString();
            return p1 === "true" && uAssoc === "true" && jobExists === "true";
          } catch(e) {
            return false;
          }
        },
        quiz: {
          question: "What does this Capstone Project connect together inside the Rails MVC environment?",
          options: ["Models validations, database relationships, controller requests, routing, background enqueuing, and email templates rendering", "HTML compilers only", "IRB console shells", "SQLite connection config settings"],
          correct: 0,
          rationale: "The final capstone integrates validations, associations, controller scopes, ActiveJob, and routing configurations into a working full-stack ecosystem."
        }
      }
    ]
  }
];
